Create npm heroku command (#9)
* Create configure_npm_for_heroku script

* Create command

* Add heroku test app to circleci dir

* Add a new test

* fix shellcheck errors

* include heroku test job in workflow

* include heroku orb and add heroku install command

* move test app one dir above

* try relative path

* add working_dir to orb command

* move back to circleci dir and add cd step

* move one one dir to avoid issues...

* add a pwd to see where this script is running

* try setting the working dir at the job level

* try new paths

* try moving back to .circleci dir

* remove change dir

* try cd step once more without the working dir

* add cd correctly

* add a pwd echo to script

* try adding new path vars

* try new way of referencing orb command

* remove bad cd

* add working_dir param for test

* fix shellcheck for cd error

* fix eof error

* add -f flag to force push and overwrite current heroku git

* add working dir to command push

* try a manual cd into the dir

* manually set nodejs buildpack

* add heroku app name to buildpacks set command

* try setting npm_config_prefix

* try to copy all of subdir into root

* get all files

* try root dir

* Revert "try root dir"

This reverts commit ff8082697f7df5224c2a5cce81c42882d9036929.

* try project/

* try moving cp step to pre-heroku cli install

* trying doing build script

* remove build script

* add some test steps

* change steps

* change test to grep inside package.json

* clean up test

* fix example name

* rename example to reflect command

* remove working dir in example.

* try intentionally break the test

* try breaking test

* include orbs in orb.yml

* add heroku and jq install to command

* check if jq is installed and use jq in block

* add jq check for malformed and fix package.json

* change jq validation

* try new jq

* add some echos

* Update src/examples/confgure_npm_for_heroku.yml

Co-authored-by: robertboulton <robert.boulton@ft.com>

* Update src/examples/confgure_npm_for_heroku.yml

Co-authored-by: robertboulton <robert.boulton@ft.com>

* remove extra elif

* remove unneeded heroku/install in example

* change error message

* change else to elif

* intentionally break app_name for testing

* add error check

* now revert broken app name change

* change description on command

* add verbose explanation for existing prebuild script

* add heroku-prebuild for test

* remove double \

* remove test heroku-prebuild

* Update src/scripts/configure_npm_for_heroku.sh

Co-authored-by: robertboulton <robert.boulton@ft.com>

* Update src/examples/confgure_npm_for_heroku.yml

Co-authored-by: robertboulton <robert.boulton@ft.com>

* Update src/examples/confgure_npm_for_heroku.yml

Co-authored-by: Rob Godfrey <rob.godfrey@gmail.com>

---------

Co-authored-by: robertboulton <robert.boulton@ft.com>
Co-authored-by: Rob Godfrey <rob.godfrey@gmail.com>

diff --git a/.circleci/test-deploy.yml b/.circleci/test-deploy.yml
--- a/.circleci/test-deploy.yml
+++ b/.circleci/test-deploy.yml
@@ -3,6 +3,7 @@ orbs:
   # Your orb will be automatically injected here during the pipeline.
   # Reference your orb's jobs and commands below as they will exist when built.
   orb-tools: circleci/orb-tools@12.1
+  heroku: circleci/heroku@2.0
   # The orb definition is intentionally not included here. It will be injected into the pipeline.
   cloudsmith-npm: {}
 
@@ -20,7 +21,6 @@ release-filters: &release-filters
     only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
 
 jobs:
-
   test-set_env_vars_for_npm:
     docker:
       - image: cimg/node:20.12
@@ -141,6 +141,30 @@ jobs:
           command: npm publish
           working_directory: .circleci/simple-npm-package-test
 
+  test-configure_npm_for_heroku:
+    docker:
+      - image: cimg/node:20.12
+    steps:
+      - checkout
+      - cloudsmith-npm/configure_npm_for_heroku:
+          repository: "circleci-orb-testing"
+          app_name: "heroku-cloudsmith"
+          working_directory: ".circleci/heroku-cloudsmith-circleci-test"
+      - run:
+          name: Test if package.json contains heroku prebuild script
+          command: |
+            if ! grep -q "heroku-prebuild" .circleci/heroku-cloudsmith-circleci-test/package.json
+            then
+              echo "Test failed: package.json does not contain heroku-prebuild script."
+              exit 1
+            fi
+            if ! grep -q "npm config set $NPM_REGISTRY" .circleci/heroku-cloudsmith-circleci-test/package.json
+            then
+              echo "Test failed: package.json does not contain NPM REGISTRY."
+              exit 1
+            fi
+            echo "All tests passed."
+
 workflows:
   test-deploy:
     jobs:
@@ -167,6 +191,9 @@ workflows:
       - test-upload_package_native:
           context: circleci-orb-publishing
           filters: *filters
+      - test-configure_npm_for_heroku:
+          context: circleci-orb-publishing
+          filters: *filters
       # The orb must be re-packed for publishing, and saved to the workspace.
       - orb-tools/pack:
           filters: *release-filters
@@ -184,6 +211,7 @@ workflows:
             - test-set_env_vars_for_npm_install_package
             - test-upload_package_using_cli
             - test-upload_package_native
+            - test-configure_npm_for_heroku
           # Use a context to hold your publishing token.
           context: circleci-orb-publishing
           filters: *release-filters
