Refactor download commands (#5)
* change npm upload script

* fix filename error in dir

* move oidc to orb

* try sudo but this will probably fail...

* change file extension to .tgz instead of .tar.gz

* fix examples and add npm native command and test

* try including orbs block

* remove extra oidc command

* remve extra backticks on context

* include cloudsmith python orb in orb packing

* try adding repo env var to command

* remove dist_dir from npm publish test

* add alpine test for cli upload

* fix docker image name

* remove alpine and apk build stuff.

* change wording in shell script

* change python and cli install to run steps and remove from script

* remove extra python3

* remove ensurepip

* add oidc command correctly

* remove extra configure defaults

* change pip install to python3

* remove ensurepip and revert to pip3

* remove cloudsmith python orb reference

* try moving env vars around

* try adding in command and re-name auth var

* fix echo shellcheck

* fix small errors

* rename create_npmrc to configure_npm and refactor commands

* rename commands, env vars and other changes

* correctly mask auth token in pipeline echo

diff --git a/.circleci/test-deploy.yml b/.circleci/test-deploy.yml
--- a/.circleci/test-deploy.yml
+++ b/.circleci/test-deploy.yml
@@ -32,14 +32,19 @@ jobs:
       - run:
           name: Assert environment variables have been set
           command: |
-            if [ $CLOUDSMITH_DOWNLOADS_DOMAIN != "packages.ft.com" ]
+            if [ -z $CLOUDSMITH_NPM_REGISTRY ]
             then
-              echo "Test failed: CLOUDSMITH_DOWNLOADS_DOMAIN has not been set correctly."
+              echo "Test failed: CLOUDSMITH_NPM_REGISTRY has not been set."
               exit 1
             fi
-            if [ -z $NPM_REGISTRY_URL ]
+            if [ -z $CLOUDSMITH_NPM_AUTH_CONFIG ]
             then
-              echo "Test failed: NPM_REGISTRY_URL has not been set."
+              echo "Test failed: CLOUDSMITH_NPM_AUTH_CONFIG has not been set."
+              exit 1
+            fi
+            if [ -z $CLOUDSMITH_NPM_REGISTRY_WITH_AUTH_CONFIG ]
+            then
+              echo "Test failed: CLOUDSMITH_NPM_REGISTRY_WITH_AUTH_CONFIG has not been set."
               exit 1
             fi
             echo "All tests passed."
@@ -54,15 +59,15 @@ jobs:
           repository: "circleci-orb-testing"
       - run:
           name: Install an npm package
-          command: npm install simple-npm-package --registry=$NPM_REGISTRY_URL
+          command: npm install simple-npm-package --registry=$CLOUDSMITH_NPM_REGISTRY_WITH_AUTH_CONFIG
 
-  test-create_npmrc:
+  test-configure_npm:
     docker:
       - image: cimg/node:20.12
     resource_class: small
     steps:
       - checkout
-      - cloudsmith-npm/create_npmrc:
+      - cloudsmith-npm/configure_npm:
           repository: "circleci-orb-testing"
       - run:
           name: Assert .npmrc file has been created
@@ -84,16 +89,16 @@ jobs:
             fi
             echo "All tests passed."
 
-  test-create_npmrc_install_package_example:
+  test-configure_npm_install_package_example:
     docker:
       - image: cimg/node:20.12
     steps:
       - checkout
-      - cloudsmith-npm/create_npmrc:
+      - cloudsmith-npm/configure_npm:
           repository: "circleci-orb-testing"
       - run: npm install simple-npm-package
 
-  test-create_npmrc_install_package_json_example:
+  test-configure_npm_install_package_json_example:
     docker:
       - image: cimg/node:20.12
     steps:
@@ -106,7 +111,7 @@ jobs:
                 "simple-npm-package": "^1.0.0"
               }
             }' > package.json
-      - cloudsmith-npm/create_npmrc:
+      - cloudsmith-npm/configure_npm:
           repository: "circleci-orb-testing"
       - run: npm install
 
@@ -129,7 +134,7 @@ jobs:
       - image: cimg/node:20.12
     steps:
       - checkout
-      - cloudsmith-npm/create_npmrc:
+      - cloudsmith-npm/configure_npm:
           repository: "circleci-orb-testing"
       - run:
           name: publish package
@@ -144,13 +149,13 @@ workflows:
       - test-set_env_vars_for_npm:
           context: circleci-orb-publishing
           filters: *filters
-      - test-create_npmrc:
+      - test-configure_npm:
           context: circleci-orb-publishing
           filters: *filters
-      - test-create_npmrc_install_package_example:
+      - test-configure_npm_install_package_example:
           context: circleci-orb-publishing
           filters: *filters
-      - test-create_npmrc_install_package_json_example:
+      - test-configure_npm_install_package_json_example:
           context: circleci-orb-publishing
           filters: *filters
       - test-set_env_vars_for_npm_install_package:
@@ -172,9 +177,9 @@ workflows:
           # Ensure this job requires all test jobs and the pack job.
           requires:
             - orb-tools/pack
-            - test-create_npmrc
-            - test-create_npmrc_install_package_example
-            - test-create_npmrc_install_package_json_example
+            - test-configure_npm
+            - test-configure_npm_install_package_example
+            - test-configure_npm_install_package_json_example
             - test-set_env_vars_for_npm
             - test-set_env_vars_for_npm_install_package
             - test-upload_package_using_cli
